In [49]:
import numpy as np

# Carga de un documento de texto
data = np.loadtxt('data.csv', delimiter=',', skiprows=1)
#print (data)

# Carga filas complejas de un documento de texto y autocompleta / descubre
datafill = np.genfromtxt('datapersonas.csv', delimiter=',', dtype=None, names=True, encoding=None)
#print (datafill)
#print(type(datafill))

# Crea un archivo de extension .NPZ 
np.savez('datapersonas.npz',datafill)

datanpz = np.load('datapersonas.npz')
print ("Iteracion del NPZ")
for item in datanpz.files:
    print (item)
    print(datanpz[item])



Iteracion del NPZ
arr_0
[('John', 28, 175, 70) ('Alice', 24, 160, 55) ('Bob', 30, 180, 80)
 ('Diana', 22, 165, 60)]


In [53]:
import numpy as np
l = [1,2,3,4,5]
t = (1,2,3,4,5)
s = {1,2,3,4,5}
arr = np.array(s)
print (arr)
print (type(arr))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


In [57]:
d = np.arange(0,100,2)
print (d)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [83]:
d = np.linspace(0,100,99)
print (d)

[  0.           1.02040816   2.04081633   3.06122449   4.08163265
   5.10204082   6.12244898   7.14285714   8.16326531   9.18367347
  10.20408163  11.2244898   12.24489796  13.26530612  14.28571429
  15.30612245  16.32653061  17.34693878  18.36734694  19.3877551
  20.40816327  21.42857143  22.44897959  23.46938776  24.48979592
  25.51020408  26.53061224  27.55102041  28.57142857  29.59183673
  30.6122449   31.63265306  32.65306122  33.67346939  34.69387755
  35.71428571  36.73469388  37.75510204  38.7755102   39.79591837
  40.81632653  41.83673469  42.85714286  43.87755102  44.89795918
  45.91836735  46.93877551  47.95918367  48.97959184  50.
  51.02040816  52.04081633  53.06122449  54.08163265  55.10204082
  56.12244898  57.14285714  58.16326531  59.18367347  60.20408163
  61.2244898   62.24489796  63.26530612  64.28571429  65.30612245
  66.32653061  67.34693878  68.36734694  69.3877551   70.40816327
  71.42857143  72.44897959  73.46938776  74.48979592  75.51020408
  76.53061224  77.5

In [113]:
# El parametro que recibe un Shape()
d = np.zeros((2,2,2,2))
print (d)

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


In [117]:
d = np.ones((2,2,2,2))
print (d)

[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]


In [143]:
d = np.random.rand(2,3,5,5)
print(d)

[[[[0.77319602 0.65828804 0.66846439 0.0013413  0.38303477]
   [0.98518257 0.50168904 0.95939991 0.87827808 0.56697886]
   [0.62665468 0.06908125 0.26930664 0.11216877 0.81622674]
   [0.73090271 0.47904168 0.50974242 0.43478394 0.47736869]
   [0.42146252 0.89803534 0.64015014 0.78687601 0.60215015]]

  [[0.61937585 0.41944563 0.07974093 0.62609217 0.55854389]
   [0.51130937 0.06765347 0.53314483 0.72807491 0.22111595]
   [0.40726947 0.10517954 0.0580355  0.17296001 0.74209486]
   [0.13919042 0.7602219  0.74656    0.48973337 0.22685018]
   [0.30915765 0.04833249 0.91314061 0.7309218  0.81612134]]

  [[0.19142597 0.87597686 0.15980485 0.52452682 0.34369529]
   [0.22613741 0.47737702 0.74218367 0.73502416 0.00480339]
   [0.63777697 0.1181702  0.82558235 0.8219937  0.87469336]
   [0.4136303  0.45015509 0.53920518 0.28280739 0.57627385]
   [0.01708304 0.12303787 0.53838283 0.67464336 0.16190421]]]


 [[[0.25272225 0.61798088 0.10352562 0.15544683 0.88173436]
   [0.89289833 0.58616932 0.5412

In [171]:
arr = np.random.rand(2,2,3,3,3,3,3)
suma = np.sum(arr)
my_mean = np.mean(arr)
my_average = np.average(arr)
my_var = np.var(arr)
my_std = np.std(arr)

print (arr)
print(suma, my_mean, my_average, my_var, my_std)

[[[[[[[0.24380079 0.69660384 0.38674971]
      [0.46926353 0.49695323 0.38192644]
      [0.12047443 0.67809895 0.10562581]]

     [[0.67496653 0.49099196 0.67261495]
      [0.64038037 0.78652549 0.25588284]
      [0.2805215  0.96629989 0.2162311 ]]

     [[0.94771813 0.56355549 0.57969095]
      [0.81802144 0.26687687 0.71829397]
      [0.90830904 0.50611476 0.87264253]]]


    [[[0.05236059 0.441538   0.2224862 ]
      [0.74129884 0.41433028 0.63681866]
      [0.4596197  0.66332206 0.59260369]]

     [[0.96139055 0.85587578 0.85783437]
      [0.26130353 0.45336429 0.84310949]
      [0.09194387 0.71702326 0.17345927]]

     [[0.8955205  0.38517603 0.92612038]
      [0.54089872 0.1738783  0.87167757]
      [0.00482901 0.7041762  0.1174258 ]]]


    [[[0.77514795 0.59839616 0.30903034]
      [0.28749227 0.83112017 0.76265028]
      [0.31522095 0.52009983 0.79666881]]

     [[0.22376857 0.46738715 0.18794391]
      [0.72853152 0.87642242 0.60045012]
      [0.50806693 0.52759845 0.86575259

In [149]:
print (arr)

[[0.29516765 0.46209439]
 [0.12328196 0.12972856]]


In [151]:
print (arr)

[[0.29516765 0.46209439]
 [0.12328196 0.12972856]]


In [161]:
print (np.random.rand(2,2))

[[0.27924947 0.4237739 ]
 [0.72131762 0.19998472]]


In [191]:
bigdata = np.arange(0,1000,3)
#print (bigdata)
#print (len(bigdata))
#print (bigdata % 5 == 0)
#print (bigdata[bigdata % 5 == 0])

In [211]:
bigdata = np.arange(100,0,-1)
print (bigdata)

indices = np.where(bigdata % 5 == 0)
print ("Solo los indices")
print (indices[0])
print ("Los valores")
print (bigdata[indices])

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1]
Solo los indices
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
Los valores
[100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15
  10   5]
