In [1]:
concentraciones = [10,200,3000,5]
minimo = min(concentraciones)
maximo = max(concentraciones)

datos_nor = [ (x - minimo) / (maximo-minimo) for x in concentraciones]
print (datos_nor)

[0.001669449081803005, 0.0651085141903172, 1.0, 0.0]


In [7]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = {
    'Mineral':['A','B','C','D'],
    'Concentracion':[10,200,3000,5]
}
df = pd.DataFrame(data)
scaler = MinMaxScaler()
print (scaler.fit_transform(df[['Concentracion']]))

[[0.00166945]
 [0.06510851]
 [1.        ]
 [0.        ]]


In [21]:
import numpy as np
########0,1,2,3,4, 5,6
data = [1,4,5,7,8,10,50]
arr = np.array(data)
print (type(arr))

filtrado = filter(lambda x: x > 5,data)
print (list(filtrado))

indices = np.where(arr > 5)
print(indices)
print(indices[0])
for i in indices:
    print(str(arr[i]) + "\n")

<class 'numpy.ndarray'>
[7, 8, 10, 50]
(array([3, 4, 5, 6], dtype=int64),)
[3 4 5 6]
[ 7  8 10 50]



In [29]:
import numpy as np
########0,1,2,3,4, 5,6
data = [[1,4,10],[5,7,8],[1,10,50]]
arr = np.array(data)
print (type(arr))

#filtrado = filter(lambda x: x > 5,data)
#print (list(filtrado))

indices = np.where(arr > 5)
print(indices)
#print(indices[0])
#for i in indices:
#    print(str(arr[i]) + "\n")

<class 'numpy.ndarray'>
(array([0, 1, 1, 2, 2], dtype=int64), array([2, 1, 2, 1, 2], dtype=int64))


In [71]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
producto = np.dot(a,b)
a_std = np.std(a)
print (producto)
print (f'STD:{a_std}')
print (f'STD:{np.std(b)}')
print (f'Mean:{np.mean(a)}')
print (f'Sun:{np.sum(b)}')

maxtrix = np.random.rand(100,1)
print (np.std(maxtrix[0]))
print (maxtrix)

32
STD:0.816496580927726
STD:0.816496580927726
Mean:2.0
Sun:15
0.0
[[0.87333209]
 [0.69442335]
 [0.01609256]
 [0.99375911]
 [0.29010592]
 [0.56885736]
 [0.0068753 ]
 [0.96547689]
 [0.5822705 ]
 [0.84839195]
 [0.68789209]
 [0.96307379]
 [0.96828553]
 [0.26112389]
 [0.36878058]
 [0.99951992]
 [0.07601877]
 [0.7339686 ]
 [0.58808146]
 [0.30655113]
 [0.91498397]
 [0.09592709]
 [0.192631  ]
 [0.97560794]
 [0.18579117]
 [0.31956774]
 [0.34974217]
 [0.9913029 ]
 [0.39791139]
 [0.94686981]
 [0.90738706]
 [0.28902003]
 [0.18562742]
 [0.5551474 ]
 [0.7312037 ]
 [0.08190294]
 [0.52514683]
 [0.54304135]
 [0.5642528 ]
 [0.03731789]
 [0.95345468]
 [0.5365523 ]
 [0.59299695]
 [0.54732153]
 [0.34189516]
 [0.68473278]
 [0.06311824]
 [0.53716524]
 [0.2702967 ]
 [0.28637016]
 [0.16213559]
 [0.81207321]
 [0.71429469]
 [0.21783403]
 [0.3704895 ]
 [0.47084994]
 [0.86992468]
 [0.21814001]
 [0.87971051]
 [0.97207029]
 [0.0462052 ]
 [0.40717546]
 [0.3195747 ]
 [0.44358375]
 [0.12684322]
 [0.12724785]
 [0.19735